name: ${project.parent.artifactId}
version: '${project.parent.version}'
main: me.whereareiam.tabster.spigot.TabsterSpigot
api-version: '1.18'
author: whereareiam
softdepend: [
  LuckPerms
]

libraries:
  - com.google.inject:guice:${guice.version}
  - net.elytrium:serializer:${serializer.version}
  - net.kyori:adventure-platform-bukkit:${adventure-platform-bukkit.version}
  - net.kyori:adventure-text-serializer-plain:${adventure.version}
  - net.kyori:adventure-text-minimessage:${adventure.version}