name: Development

on:
  push:
    branches:
      - dev

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      projectName: ${{ steps.project_details.outputs.project_name }}
      projectVersion: ${{ steps.project_details.outputs.project_version }}

    steps:
      - uses: actions/checkout@v4
      - name: Extract project details
        id: project_details
        run: |
          echo "PROJECT_NAME=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.artifactId}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
          echo "PROJECT_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

  velocity:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build Velocity
        run: |
          mvn -pl core,velocity -B -P dev package --file pom.xml
      - name: Upload artifact
        env:
          projectName: ${{ needs.setup.outputs.projectName }}
          projectVersion: ${{ needs.setup.outputs.projectVersion }}
        uses: actions/upload-artifact@v4
        with:
          name: paper-artifact
          path: paper/target/$projectName-VELOCITY-$projectVersion.jar

  spigot:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build Spigot
        run: |
          mvn -pl core,spigot -B -P dev package --file pom.xml
      - name: Move artifact
        env:
          projectName: ${{ needs.setup.outputs.projectName }}
          projectVersion: ${{ needs.setup.outputs.projectVersion }}
        run: |
          mv spigot/target/$projectName-SPIGOT-$projectVersion.jar ${{ github.workspace }}/
      - name: Upload artifact
        env:
          projectName: ${{ needs.setup.outputs.projectName }}
          projectVersion: ${{ needs.setup.outputs.projectVersion }}
        uses: actions/upload-artifact@v4
        with:
          name: paper-artifact
          path: paper/target/$projectName-SPIGOT-$projectVersion.jar

  paper:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build Paper
        run: |
          mvn -pl core,paper -B -P dev package --file pom.xml
      - name: Upload artifact
        env:
          projectName: ${{ needs.setup.outputs.projectName }}
          projectVersion: ${{ needs.setup.outputs.projectVersion }}
        uses: actions/upload-artifact@v4
        with:
          name: paper-artifact
          path: paper/target/$projectName-PAPER-$projectVersion.jar