name: Development

on:
  push:
    branches:
      - dev

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Extract project details
        id: project_details
        run: |
          echo "PROJECT_NAME=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.artifactId}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
          echo "PROJECT_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Build with Maven
        run: |
          mvn -B -P dev package --file pom.xml

  moveArtifacts:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Move Artifacts to Common Directory
        run: |
          mv velocity/target/${{ needs.setup.outputs.PROJECT_NAME }}-VELOCITY-${{ needs.setup.outputs.PROJECT_VERSION }}.jar ${{ github.workspace }}/
          mv spigot/target/${{ needs.setup.outputs.PROJECT_NAME }}-SPIGOT-${{ needs.setup.outputs.PROJECT_VERSION }}.jar ${{ github.workspace }}/
          mv paper/target/${{ needs.setup.outputs.PROJECT_NAME }}-PAPER-${{ needs.setup.outputs.PROJECT_VERSION }}.jar ${{ github.workspace }}/

  uploadArtifacts:
    needs: move_artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Tabster-b${{ github.run_number }}
          path: ${{ github.workspace }}/*.jar